### ISSUE TITLE
Could have a callback closure on completion of the tweening ?

### ISSUE THREAD

**Issue by jibeex** [RobinFalko/Ubergang#2]
Hello,

Great job! Fantastic work! Exactly what I need. Thank you ! 

A small improvement could be having a callback closure on completion of the tweening. What do you think ?

regards,
Jianbin

**Comment by RobinFalko** [comment]
Hello jibeex,

thank you for the kind words, I really appreciate that.
There is a completion closure available already, but I just noticed that I didn't add an example for that. Will do this asap.

Anyway you can add a completion closure by writing `tween.complete { ... }`

```
let tween = NumericTween<Int>(id: "tween")
            .to( 100,
                 from: 0,
                 update: {
                    print("update")
                },
                 duration: 5)
            .complete {
                print("complete")
            }
```
